# Minimal configs; override in notebooks as needed.
CFG = {
    'scale': 4,
    'hr_crop': 128,
    'train': {
        'batch_size': 16,
        'num_workers': 4,
        'epochs': 100,
        'lr': 1e-4,
        'loss': 'l1',
        'val_batch_size': 32,
        'use_amp': False,
        'resume': False,
        'load_pretrained_model': False,
        'pretrained_path': 'weights/SRResNet_x4-ImageNet.pth.tar',
        'checkpoint_path': 'weights/srresnet_{loss}_checkpoint.pth',
        'lr_step': 50,
        'lr_gamma': 0.5,
    },
    'gan': {
        'batch_size': 8,
        'train_batch_size': 8,
        'val_batch_size': None,
        'num_workers': 4,
        'epochs': 200,
        'lr_g': 1e-4,
        'lr_d': 1e-4,
        'use_amp': False,
        'g_steps': 1,
        'd_steps': 1,
        'adv_weight': 1e-3,
        'perc_weight': 6e-3,
        'pixel_weight': 1.0,
        'r1_weight': 0.0,
        'real_label': 0.9,
        'fake_label': 0.0,
        'init_gen_path': None,
        'resume': False,
        'checkpoint_path': 'weights/gan_checkpoint.pth',
    },
    'paths': {
        'train_lr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/train/train_lr',
        'train_hr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/train/train_hr',
        'val_lr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/val/val_lr',
        'val_hr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/val/val_hr',
        'test_lr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/test/test_lr',
        'test_hr': '../../input/anh-ve-tinh-2/Anh_ve_tinh_2/test/test_hr',
    },
}
